updated workflow config

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,32 +1,58 @@
-name: CI
+name: Deploy to GitHub Pages
 
 on:
   push:
-    branches: [main]
+    branches: ["main"]
   pull_request:
-    branches: [main]
+    branches: ["main"]
 
   workflow_dispatch:
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v3
 
-      - name: install
-        run: npm i --legacy-peer-deps
+      - name: Setup Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: "18"
+          cache: "npm"
 
-      - name: build
+      - name: Install Dependencies
+        run: |
+          npm install
+          npm install @rollup/rollup-linux-x64-gnu
+
+      - name: Build Project
         run: npm run build
         env:
-          BASE_PATH: /Sorting-Algorithm-Visualization/
+          NODE_ENV: production
 
-      - name: create .nojekyll
-        run: touch .output/public/.nojekyll
+      - name: Configure SSG
+        run: |
+          mkdir -p dist
+          [ -f dist/index.html ] && cp dist/index.html dist/404.html || echo "index.html not found"
 
-      - name: deploy pages
-        uses: JamesIves/github-pages-deploy-action@v4.5.0
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
         with:
-          branch: gh-pages
-          folder: .output/public
+          path: "./dist"
+
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
